server:
  assets-path: /app/assets

theme:
  light: false                 # Switch to dark theme
  background-color: 0 0 0      # Pure black background
  primary-color: 120 100 50    # Neon green
  positive-color: 120 100 50   # Same neon green for positive indicators
  negative-color: 0 100 50     # Bright red for negative indicators
  contrast-multiplier: 1.3     # Increased contrast for better readability on black

branding:
  logo-text: myDash
  # If you want to use a custom image instead of text:
  logo-url: /assets/mydash-logo-2.png
  favicon-url: /assets/mydash-logo-2.png
  custom-footer: |
    <p>myDash - Personal Dashboard</p>
    

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  !include: home.yml
  #!include: learning.yml
  #!include: growing.yml
  #!include: sports.yml