- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: rss
          limit: 10
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://steelersdepot.com/feed/
              title: Steelers Depot (News)
            - url: https://www.mlb.com/pirates/feeds/news/rss.xml
              title: Pittsburgh Pirates News
            - url: https://www.dukebasketballreport.com/rss/current.xml
              title: Duke Basketball Report
            - url: https://www.theverge.com/rss/index.xml
              title: The Verge (Tech)
            - url: https://feeds.a.dj.com/rss/RSSMarketsMain.xml
              title: WSJ Markets
            - url: https://blog.google/technology/ai/rss/
              title: Google AI Blog
            - url: https://desiring-god.herokuapp.com/rss
              title: Desiring God

        - type: weather
          location: Tampa
          units: imperial 
          hour-format: 12h

    - size: full
      widgets:
        - type: group
          widgets:
            - type: reddit
              subreddit: worldnews
              show-thumbnails: true
            - type: reddit
              subreddit: todayilearned
              show-thumbnails: true

        - type: videos
          channels:
            - UC9RM-iSvTu1uPJb8X5yp3EQ # Philip Anthony Mitchell
            - UC2C_jShtL725hvbm1arSV9w # CGP Grey
            - UC0QHWhjbe5fGJEPz3sVb6nw # PBS Space Time
            - UCSHZKyawb77ixDdsGog4iWA # Lex Fridman
            - UC9-y-6csu5WGm29I7JiwpnA # Computerphile
            - UCxsQFG_8Dbt1W89vhUiXbXA # Practical Engineering

        - type: group
          widgets:
            - type: reddit
              subreddit: artificial
              show-thumbnails: true
            - type: reddit
              subreddit: MachineLearning
              show-thumbnails: true
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: investing
              show-thumbnails: true
            - type: reddit
              subreddit: StockMarket
              show-thumbnails: true

    - size: small
      widgets:
        - type: markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: XRP-USD
              name: Ripple
            - symbol: SOL-USD
              name: Solana
            - symbol: TSLA
              name: Tesla
            - symbol: GDXU
              name: GDXU