- name: Learning
  columns:
  - size: small
    widgets:
      - type: bookmarks
        groups:
          - title: Finance Resources
            color: 110 70 50
            links:
              - title: Yahoo Finance
                url: https://finance.yahoo.com/
                icon: si:yahoo
              - title: Trading View
                url: https://www.tradingview.com/
                icon: si:tradingview
              - title: WSJ
                url: https://www.wsj.com/
                icon: si:wsj
              - title: Investopedia
                url: https://www.investopedia.com/
          
          - title: Tech Learning
            color: 200 70 50
            links:
              - title: GitHub
                url: https://github.com/
                icon: si:github
              - title: Stack Overflow
                url: https://stackoverflow.com/
                icon: si:stackoverflow
              - title: Coursera
                url: https://www.coursera.org/
                icon: si:coursera

  - size: full
    widgets:
      - type: group
        title: Financial Learning
        widgets:
          - type: reddit
            title: Personal Finance
            subreddit: personalfinance
            show-thumbnails: true
            collapse-after: 6
          - type: reddit
            title: Investing
            subreddit: investing
            show-thumbnails: true
            collapse-after: 6
          - type: rss
            title: Finance News
            style: horizontal-cards
            limit: 8
            collapse-after: 4
            cache: 3h
            feeds:
              - url: https://feeds.a.dj.com/rss/RSSMarketsMain.xml
                title: WSJ Markets
              - url: https://www.cnbc.com/id/20910258/device/rss/rss.html
                title: CNBC Finance
      
      - type: group
        title: AI & Technology
        widgets:
          - type: reddit
            title: Artificial Intelligence
            subreddit: artificial
            show-thumbnails: true
            collapse-after: 6
          - type: reddit
            title: Machine Learning
            subreddit: MachineLearning
            show-thumbnails: true
            collapse-after: 6
          - type: rss
            title: Tech News
            style: horizontal-cards
            limit: 8
            collapse-after: 4
            cache: 3h
            feeds:
              - url: https://www.theverge.com/rss/index.xml
                title: The Verge
              - url: https://blog.google/technology/ai/rss/
                title: Google AI Blog

  - size: small
    widgets:
      - type: markets
        title: Market Overview
        markets:
          - symbol: SPY
            name: S&P 500
          - symbol: BTC-USD
            name: Bitcoin
          - symbol: TSLA
            name: Tesla
          - symbol: AAPL
            name: Apple
          - symbol: MSFT
            name: Microsoft
          - symbol: NVDA
            name: NVIDIA

      - type: reddit
        title: Tech News
        subreddit: technology
        show-thumbnails: true
        collapse-after: 2